### ISSUE TITLE
Add filters/search bar

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/engage#41]

**Comment by nikochiko** [comment]
I thought about the design for this.
The most frequent action on the submissions page would be to find out submissions from previous day's problem set, and review them one by one.
IMO, the optimal design would be a dropdown for problem set and checkbox for selecting "Reviewed", "Unreviewed".
There can be a toggle-able search bar hidden by default.

**Comment by anandology** [comment]
On Thu, Jul 21, 2022 at 5:57 PM Kaustubh Maske Patil <
***@***.***> wrote:

> I thought about the design for this.
> The most frequent action on the submissions page would be to find out
> submissions from previous day's problem set, and review them one by one.
> IMO, the optimal design would be a dropdown for problem set and checkbox
> for selecting "Reviewed", "Unreviewed".
> There can be a toggle-able search bar hidden by default.
>

Fair. But the other possibilities are looking at all submissions of a
person, for a problem set or all problem sets. Another possibility would be
to review all submissions for one particular problem. That means you'll
need to add 3 dropdowns and one checkbox.


That Message ID: ***@***.***>
>
>

**Comment by nikochiko** [comment]
Too many dropdowns wouldn't be simple enough for the user.

I think we could approach this in two ways:
1. Make search bar powerful enough to handle queries like this
2. Hide the extra dropdowns and make them toggle-able

I'm not sure if one would be better than other. What do you think?

**Comment by nikochiko** [comment]
I have added a filters-bar.
For a search bar, a good idea would be to have a single search bar that will be able to search through both problems and authors.

**Comment by nikochiko** [comment]
I am adding a dropdown for both problem and author.
It would be the way with the least unknowns. We already have a dropdown for problem set, it would be similar.
A proper search bar would take a good amount of design and implementation effort.

**Comment by nikochiko** [comment]
This is implemented.
Deployment is on halt due to a FrappeCloud issue.
