### ISSUE TITLE
Progress Report Page

### ISSUE THREAD

**Issue by anandology** [pipalacademy/engage#50]
Add a page to show the current progress of the participants of a training. 

It should be a table with the following format.

|  Name | Day 1 (8) | Day 2 (7) | Total (16) |
| --- | --- | --- | --- |
| Alice | 5 | 3 | 8 |
| Bob | 6 | 1 | 7 |

The number in brackets is the number of problems in the problem set. It can also be shown as two lines, as follows:

**Day 1** 
8 problems

Sort the table by the name of the person by default. 

## Good to have
Is is not required, but would like to have the ability to sort  a column using something like [Frappe Data Table](https://frappe.io/datatable/).

Also, it would be nice to have the ability to export this as excel sheet.

**Comment by nikochiko** [comment]
@anandology is it good enough what we currently have?
the page is very slow to load, but i feel the optimisations should be a separate issue. i looked at the get_context code with a profiler, and the database queries are surprisingly fast. the bottleneck must be somewhere during the template rendering and needs to be looked at separately.

**Comment by anandology** [comment]
I think the performance is good enough for now.  

Currently all rows are not visible and there is a vertical slider. Please make sure the table is completely visible and there is no slider.

**Comment by anandology** [comment]
Also, link it from the main training page.

**Comment by nikochiko** [comment]
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/37668193/179465594-3c72a2ff-d384-4a02-a803-48e4433e752c.png">

added like this for now. we can make it better with the new mockups
