### ISSUE TITLE
Feature: Problem set definitions as YAML similar to problem repository

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/engage#65]
Goal: to make it easier to create problem sets. At the moment, the trainer needs to "Update problems" in problem repository and then add them individually to the problem set without autocomplete.

It would be better if:
1. The problem sets can be defined as a YAML file with the names of the contained problems
2. The trainer doesn't need to login to Engage and "Update problems" or something similar for the changes to take effect

**Approach:**

There are two approaches:
1. Add `git_repository` and `file_path` fields to Problem Set DocType in Engage, where the problem set definition will be fetched from. This will create problem set with the mentioned problems. Then we will need an API endpoint (unauthenticated is OK) that will take the name of the problem set and run the "update" problem set operation.
2. Use frappe API from github actions to create/update problem set with the defined problems. The problem set YAMLs list can be a variable in the github action definition. We can get a Frappe REST API token from the app. (https://frappeframework.com/docs/v14/user/en/api/rest)

I think the second approach will be better and faster to deploy.

**Comment by anandology** [comment]
I suggest creating a server script from the desk that would take a problems sets description as JSON and updates all the problem sets for a trianing.

**Comment by anandology** [comment]
The API:

```
POST /api/method/update-problem-sets

{
    "training": "2023/intermediate-python-linkedin",
    "problem_sets": [{
            "slug": "pset1",
            "title": "Problem Set 1",
            "published": true,
            "problems": [
                "python/square",
                "python/digit-count"
            ]
        },
        {
            "slug": "pset2",
            "title": "Problem Set 2",
            "published": false,
            "problems": [
                "python/sumfile",
                "python/reverse-words"
            ]
        }
    ]
}
```

The problem set name is not specified here. That will be autogenerated from the training name and the slug. It would be `pset1-2023-imtermediate-python-linkedin` for the first problem set. If the problem set is not present, it will be created and then it is linked to the training. It should be possible to unlink a problem set from a training, just by calling the API after removing it from the JSON.

**Comment by anandology** [comment]
@nikochiko please review.

**Comment by anandology** [comment]
There is no need to worry about github actions for now, I can run it manually.

**Comment by nikochiko** [comment]
Okay, that looks good :+1:

I'll add this.

**Comment by anandology** [comment]
Create a test training on linkedin.pipal.in and try using that. Please add me to that training so that I can also test it.

**Comment by nikochiko** [comment]
@anandology It is added. Please try it out!

**Comment by nikochiko** [comment]
> The problem set name is not specified here. That will be autogenerated from the training name and the slug. It would be pset1-2023-imtermediate-python-linkedin

The problem set name is being generated automatically from the title and i'm not able to change it. I think that's okay because it's still consistent

**Comment by anandology** [comment]
How will you update it if you can't set the name?

**Comment by nikochiko** [comment]
Added in https://github.com/pipalacademy/engage/commit/6cc3a59696af378a959fb349773944bf03d25ffe
